services:
  odoo:
    restart: 'no'
    ports:
      - 8069:8069
      - 8070:8070
      - 8071:8071
      - 8072:8072

  postgres:
    restart: 'no'
    ports:
      - 5432:5432

  nginx:
    restart: 'no'

  nginx-proxy:
    restart: 'no'
    ports:
      - 80:80
      - 443:443

  traefik: 
    restart: 'no'
    ports:
      - 80:80
      - 443:443

  acme-companion:
    restart: 'no'

  keydb:
    restart: 'no'

  minio:
    restart: 'no'

  pgadmin:
    restart: 'no'
